### ISSUE TITLE
Why my code cannot use "match"

### ISSUE THREAD

**Issue by Iwan-LMX** [Maka314/COMP9021_Ass1_test#18]
My code has the function of "match", so when I run this start_test.py, the output file says syntax err about my match function. However, my code is able to run in ED.
After exchange all of my match function with if(), then it well processed...
Very confusing.....

**Comment by Maka314** [comment]
My assumption is that you have multiple python environments installed in your local environment.
Because match is a new feature of python3.10, maybe the way you usually use python is to enter "python start_test.py" directly in the terminal.
In the test script, the command to call python is "python3". If python and python3 point to different versions respectively, this may happen.

**Comment by Iwan-LMX** [comment]
thanks😘Best regard，Iwan LiOn 22 Oct 2023, at 6:42 pm, Mingchen Ju ***@***.***> wrote:﻿
My assumption is that you have multiple python environments installed in your local environment.
Because match is a new feature of python3.10, maybe the way you usually use python is to enter "python start_test.py" directly in the terminal.
In the test script, the command to call python is "python3". If python and python3 point to different versions respectively, this may happen.
